"""
Brute-force metadata key - Phase 3.

KEY OBSERVATION from Phase 2:
The encrypted 4-byte LE dwords are MONOTONICALLY DECREASING:
  [0]  0xC1C21EF0
  [4]  0xBDA8B6CC
  [8]  0xB85C5C84
  [12] 0xB7B55B88
  [16] 0xB3D4823C
  ...
  [60] 0x84603F18

This means the XOR key itself is a LARGE, smoothly varying sequence.
If plaintext is a structured header with small values (offsets, sizes),
then the encrypted values essentially ARE the key values (since small XOR big ~ big).

Hypothesis: key is a smoothly decreasing function of position.
Let's compute: key[i] ~ encrypted[i] XOR 0 (if plaintext is 0) or key[i] ~ encrypted[i] XOR small_value

Strategy: Treat the encrypted header AS the key (plaintext ~ 0 for most bytes)
and find the key generation function.
"""

import struct
import sys

METADATA_PATH = r"D:\Steam\steamapps\common\VRChat\VRChat_Data\il2cpp_data\Metadata\global-metadata.dat"
KNOWN_KEY = [0x83, 0x67, 0xAF, 0xEC]

def read_header(path, size=1024):
    with open(path, "rb") as f:
        return f.read(size)

def main():
    data = read_header(METADATA_PATH)
    FILE_SIZE = 40_512_432

    print("="*70)
    print("PHASE 3: The encrypted bytes ARE approximately the key")
    print("="*70)

    # If the metadata header has mostly small values (offsets < 40MB = 0x26A2BB0,
    # version < 35, sizes < 40MB), and the key produces the large descending pattern,
    # then the key dominates the XOR.

    # Let's look at the encrypted bytes directly as potential key bytes
    print("\nEncrypted byte values (first 64):")
    for i in range(64):
        sys.stdout.write(f"{data[i]:02X} ")
        if (i+1) % 16 == 0:
            sys.stdout.write("\n")

    # The key bytes for positions 0-3 are [0x83, 0x67, 0xAF, 0xEC]
    # The encrypted bytes at 0-3 are [0xF0, 0x1E, 0xC2, 0xC1]
    # Plaintext at 0-3 is [0x73, 0x79, 0x6D, 0x2D] = "sym-"
    # So: encrypted = plaintext XOR key

    # For the REST of the header, if plaintext values are SMALL:
    # encrypted[i] ~ key[i] (within a few bits)

    # Let's see if there's a formula for the KEY that would produce values
    # close to the encrypted bytes. The encrypted sequence (bytes) is:
    # F0, 1E, C2, C1, CC, B6, A8, BD, 84, 5C, 5C, B8, 88, 5B, B5, B7, ...

    # Wait -- let me look at this differently.
    # Let me check if key[i] = (C - i*D) mod 256 for some C, D
    # We know key[0]=0x83, key[1]=0x67
    # If linear: D = (0x83-0x67) = 0x1C = 28, C = 0x83
    # key[2] should be 0x83 - 2*28 = 131-56 = 75 = 0x4B. But actual is 0xAF. Nope.

    # Let me look at the encrypted dwords more carefully:
    print("\n\nEncrypted as LE u32 dwords:")
    enc_dwords = []
    for i in range(0, 256, 4):
        val = struct.unpack_from("<I", data, i)[0]
        enc_dwords.append(val)
        if i < 64:
            print(f"  [{i:3d}] 0x{val:08X} ({val:>12d})")

    # Differences between consecutive dwords:
    print("\n\nDifferences between consecutive encrypted dwords:")
    for i in range(min(15, len(enc_dwords)-1)):
        diff = enc_dwords[i] - enc_dwords[i+1]
        print(f"  dword[{i*4}] - dword[{(i+1)*4}] = {diff:>12d} (0x{diff & 0xFFFFFFFF:08X})")

    # =========================================================================
    # EUREKA MOMENT: Let me look at the dword differences.
    # If the key is generated by a simple counter applied to 32-bit values,
    # the pattern in dwords would be very clear.
    #
    # Let's think about this differently:
    # What if the DWORD key (treating 4 bytes as one u32) is a linear function?
    # key_dword[n] = A - B*n for the nth dword (4 bytes)
    # key_dword[0] = 0xEC_AF_67_83 (LE: 83 67 AF EC)
    # =========================================================================

    print("\n\n" + "="*70)
    print("DWORD-LEVEL KEY ANALYSIS")
    print("="*70)

    # Known key dword 0 (LE): bytes [83, 67, AF, EC] = 0xECAF6783
    key_dword_0 = 0xECAF6783
    print(f"  Key dword 0: 0x{key_dword_0:08X}")

    # Encrypted dword 0: 0xC1C21EF0
    # Plaintext dword 0: 0x2D6D7973 ("sym-" LE)
    # Verify: 0x2D6D7973 XOR 0xECAF6783 = ?
    verify = 0x2D6D7973 ^ 0xECAF6783
    print(f"  Verify: plaintext[0] XOR key_dword[0] = 0x{verify:08X}")
    print(f"  Encrypted dword[0] = 0x{enc_dwords[0]:08X}")
    assert verify == enc_dwords[0], "Mismatch!"
    print(f"  MATCH!")

    # Now: if plaintext dword[1] is version (say 29 = 0x1D),
    # then key_dword[1] = enc_dword[1] XOR 0x0000001D = 0xBDA8B6CC XOR 0x1D = 0xBDA8B6D1
    # But also 0xBDA8B6CC XOR 0x18 (=24) = 0xBDA8B6D4
    # Or 0xBDA8B6CC XOR 0x1B (=27) = 0xBDA8B6D7

    print(f"\n  Key dword 1 candidates (enc_dw[1] XOR version):")
    for v in [24, 27, 29, 31]:
        kd1 = enc_dwords[1] ^ v
        diff = key_dword_0 - kd1
        print(f"    version={v:2d}: key_dw[1]=0x{kd1:08X}, diff from dw[0]={diff:>12d} (0x{diff & 0xFFFFFFFF:08X})")

    # =========================================================================
    # KEY INSIGHT: Let me check if key_dword decreases by a CONSTANT per dword
    # key_dw[0] = 0xECAF6783
    # If version=29: key_dw[1] = 0xBDA8B6D1
    # Diff: 0xECAF6783 - 0xBDA8B6D1 = 0x2F06B0B2
    #
    # If that's the step, key_dw[2] = 0xBDA8B6D1 - 0x2F06B0B2 = 0x8EA2061F
    # Decrypt dword[2]: 0xB85C5C84 XOR 0x8EA2061F = 0x36FE5A9B ... not great
    #
    # Let me try a different approach: what if the key bytes individually decrease?
    # =========================================================================

    print("\n\n" + "="*70)
    print("BYTE-LEVEL SMOOTH KEY TEST")
    print("="*70)

    # Looking at encrypted bytes: F0 1E C2 C1 CC B6 A8 BD 84 5C 5C B8 ...
    # These don't decrease smoothly per-byte, but the 32-bit values do decrease.

    # What if key[i] = (start - i * step) & 0xFF for some start, step?
    # key[0] = start = 0x83
    # key[1] = (0x83 - step) & 0xFF = 0x67 => step = 0x83 - 0x67 = 0x1C (28)
    # key[2] = (0x83 - 2*28) & 0xFF = (131 - 56) & 0xFF = 75 = 0x4B
    # But we need 0xAF. Let's check: 0x4B != 0xAF.

    # What about different step per byte lane?
    # In the SIMD code (psrldq, etc.), operations happen on 16-byte vectors.
    # What if EACH BYTE LANE (0,4,8,12...) has its own linear progression?
    # Lane 0: key[0], key[4], key[8], key[12], ...
    # Lane 1: key[1], key[5], key[9], key[13], ...
    # etc.

    # We know key[0] = 0x83. For lane 0 (positions 0, 4, 8, ...):
    # If version=29: key[4] = enc[4] ^ 29 = 0xCC ^ 0x1D = 0xD1
    # So lane 0: 0x83, 0xD1 (if v=29). Diff = 0xD1 - 0x83 = 0x4E = 78. Increasing!

    # Lane 1: key[1]=0x67, key[5]=enc[5]^0=0xB6. Diff = 0xB6-0x67 = 0x4F = 79
    # Lane 2: key[2]=0xAF, key[6]=enc[6]^0=0xA8. Diff = 0xA8-0xAF = -7 = 0xF9
    # Lane 3: key[3]=0xEC, key[7]=enc[7]^0=0xBD. Diff = 0xBD-0xEC = -0x2F = 0xD1

    # Hmm lanes 0,1 increase by ~78-79, lanes 2,3 decrease. Not consistent.

    # =========================================================================
    # BACK TO BASICS: What if the key is NOT byte-level but DWORD-level?
    # i.e., key as 32-bit integers, and each dword in plaintext is XORed
    # with a key-dword that's generated from a formula on the DWORD INDEX.
    #
    # key_dw[0] = 0xECAF6783  (known from "sym-")
    # We need to find key_dw[1], key_dw[2], etc.
    #
    # CONSTRAINT: For this to be a valid metadata header:
    # - dword[1] (version) should be 24-31
    # - dwords[2..N] are offset/size pairs, all < FILE_SIZE (0x26A2BB0)
    #
    # Since encrypted dwords are ~0xC1...0x84 (very large), and plaintext
    # should be < 0x26A2BB0, the key dwords must be CLOSE to the encrypted dwords.
    # Specifically: key_dw[n] = enc_dw[n] XOR plaintext_dw[n]
    # where plaintext_dw[n] < 0x26A2BB0 (small relative to 0xFFFFFFFF)
    #
    # So key_dw[n] ~ enc_dw[n] (differs by at most ~0x26A2BB0 in some bits)
    # The encrypted dwords decrease smoothly. If we assume the KEY decreases
    # smoothly and plaintext is "noise" on top, we can try:
    #
    # key_dw[n] = A - B*n (linear in dword index)
    # With key_dw[0] = 0xECAF6783, find B such that:
    # plaintext_dw[1] = enc_dw[1] XOR (0xECAF6783 - B) is a valid version (24-31)
    # =========================================================================

    print("\n\n" + "="*70)
    print("LINEAR DWORD KEY: key_dw[n] = 0xECAF6783 - B*n")
    print("="*70)

    # enc_dw[1] XOR key_dw[1] should = version (24-31)
    # key_dw[1] = 0xECAF6783 - B
    # So: enc_dw[1] XOR (0xECAF6783 - B) = version
    # => 0xECAF6783 - B = enc_dw[1] XOR version
    # => B = 0xECAF6783 - (enc_dw[1] XOR version)

    for version in [24, 27, 29, 31]:
        B = (key_dword_0 - (enc_dwords[1] ^ version)) & 0xFFFFFFFF
        print(f"\n  version={version}: B = 0x{B:08X} ({B})")

        # Generate key for first 16 dwords and decrypt
        decrypted_dwords = []
        all_valid = True
        for n in range(16):
            kd = (key_dword_0 - B * n) & 0xFFFFFFFF
            pd = enc_dwords[n] ^ kd
            decrypted_dwords.append(pd)
            valid = "OK" if pd < FILE_SIZE else "BIG"
            if n > 1 and pd >= FILE_SIZE:
                all_valid = False
            if n < 8:
                print(f"    dw[{n}]: key=0x{kd:08X}, plain=0x{pd:08X} ({pd:>12d}) [{valid}]")

        if all_valid:
            print(f"  *** ALL VALID for version={version}, B=0x{B:08X} ***")
            # Show as offset/size pairs
            print(f"    Header: magic=0x{decrypted_dwords[0]:08X}, version={decrypted_dwords[1]}")
            for s in range(min(7, (len(decrypted_dwords)-2)//2)):
                off = decrypted_dwords[2 + s*2]
                sz = decrypted_dwords[3 + s*2]
                print(f"    Section {s}: offset=0x{off:08X} ({off}), size={sz}")

    # =========================================================================
    # ANOTHER MODEL: key_dw[n] = key_dw[0] * R^n mod 2^32 (multiplicative)
    # key_dw[0] = 0xECAF6783
    # key_dw[1] = 0xECAF6783 * R mod 2^32
    # We need: (0xECAF6783 * R) mod 2^32 XOR enc_dw[1] = version (24-31)
    # =========================================================================

    # This is harder to brute force. Skip for now.

    # =========================================================================
    # SIMPLEST MODEL THAT MIGHT WORK:
    # What if key[i] (byte-level) = (256 - i) & 0xFF or (C - i*D) & 0xFF
    # but with DIFFERENT values than we computed?
    #
    # Wait: re-examine. We KNOW:
    #   encrypted[i] = plaintext[i] ^ key[i]
    #   key[0..3] = [0x83, 0x67, 0xAF, 0xEC]
    #
    # These 4 bytes as a descending check:
    #   0x83=131, 0x67=103, 0xAF=175, 0xEC=236
    #   NOT monotonically descending in byte order! 131, 103 (down), 175 (up), 236 (up)
    #   But as LE u32: 0xECAF6783 which is a single large number.
    #
    # What if the key is generated as a single counter starting at some value
    # and SUBTRACTING a constant each byte position?
    # key_as_u32_LE = 0xECAF6783
    # Treat this as a 32-bit integer. The NEXT 4 bytes of key form another u32.
    # And the counter decreases.
    #
    # key_bytes[0:4] as u32 LE = 0xECAF6783
    # key_bytes[4:8] as u32 LE = 0xECAF6783 - step
    # key_bytes[8:12] as u32 LE = 0xECAF6783 - 2*step
    # ...
    #
    # Test with version=29: key_dw[1] = enc_dw[1] ^ 29 = 0xBDA8B6CC ^ 0x1D = 0xBDA8B6D1
    # step = 0xECAF6783 - 0xBDA8B6D1 = 0x2F06B0B2
    # =========================================================================

    print("\n\n" + "="*70)
    print("TESTING key_dw[n] = 0xECAF6783 - 0x2F06B0B2*n (from version=29)")
    print("="*70)

    B_v29 = 0x2F06B0B2
    # Decrypt and check
    for n in range(16):
        kd = (key_dword_0 - B_v29 * n) & 0xFFFFFFFF
        pd = enc_dwords[n] ^ kd
        valid = "OK" if pd < FILE_SIZE else "BIG"
        print(f"  dw[{n:2d}] enc=0x{enc_dwords[n]:08X} key=0x{kd:08X} plain=0x{pd:08X} ({pd:>12d}) [{valid}]")

    # =========================================================================
    # Let me also try: the key might just be the position itself in some form
    # What about: key_u32[n] = constant - n * small_step
    # where we search for small_step values that make ALL plaintext dwords < 40MB
    # =========================================================================

    print("\n\n" + "="*70)
    print("EXHAUSTIVE SEARCH: Find step B where ALL plaintext dwords[2..15] < 40MB")
    print("="*70)

    # For each candidate B (derived from assuming dword[1] = version):
    best_results = []
    for version in range(1, 100):
        kd1 = enc_dwords[1] ^ version
        B = (key_dword_0 - kd1) & 0xFFFFFFFF
        if B == 0:
            continue

        # Check dwords 2-15
        valid_count = 0
        max_plain = 0
        for n in range(2, 16):
            kd = (key_dword_0 - B * n) & 0xFFFFFFFF
            pd = enc_dwords[n] ^ kd
            if pd < FILE_SIZE:
                valid_count += 1
                max_plain = max(max_plain, pd)

        if valid_count >= 10:  # at least 10 of 14 dwords valid
            best_results.append((valid_count, version, B, max_plain))

    best_results.sort(reverse=True)
    print(f"\n  Top results (valid_count >= 10 out of 14):")
    for count, ver, step, maxp in best_results[:20]:
        print(f"    version={ver:3d}, step=0x{step:08X}, valid={count}/14, max_plain=0x{maxp:08X}")

    # =========================================================================
    # Now try non-linear: key_dw[n] = A - B*n - C*n^2
    # With key_dw[0] = 0xECAF6783
    # =========================================================================
    print("\n\n" + "="*70)
    print("QUADRATIC DWORD KEY: key_dw[n] = 0xECAF6783 - B*n - C*n^2")
    print("  Using version=29 and trying different C values")
    print("="*70)

    # key_dw[1] = A - B - C (= enc_dw[1] ^ 29 = 0xBDA8B6D1)
    # key_dw[2] = A - 2B - 4C (should produce small plaintext at dw[2])
    # plaintext_dw[2] = enc_dw[2] ^ key_dw[2] should be < FILE_SIZE
    # We want this to be a valid offset (like 0x110 = 272)

    A = key_dword_0
    # For version 29: A - B - C = 0xBDA8B6D1
    # So B + C = A - 0xBDA8B6D1 = 0x2F06B0B2

    # For dword[2] to be a header offset (try 0x110):
    # plaintext_dw[2] = enc_dw[2] ^ (A - 2B - 4C) = target_offset
    # A - 2B - 4C = enc_dw[2] ^ target_offset

    target_offsets = [0x110, 0x108, 0x100, 0x120, 0x130, 0x140, 0x150, 0x160, 0x170, 0x180]
    for target in target_offsets:
        kd2_needed = enc_dwords[2] ^ target
        # A - 2B - 4C = kd2_needed
        # B + C = 0x2F06B0B2
        # => A - 2(B+C) - 2C = kd2_needed
        # => A - 2*0x2F06B0B2 - 2C = kd2_needed
        # => 2C = A - 2*0x2F06B0B2 - kd2_needed
        two_C = (A - 2 * 0x2F06B0B2 - kd2_needed) & 0xFFFFFFFF
        if two_C % 2 != 0:
            continue
        C_val = (two_C // 2) & 0xFFFFFFFF
        B_val = (0x2F06B0B2 - C_val) & 0xFFFFFFFF

        # Verify and decrypt all dwords
        all_ok = True
        plains = []
        for n in range(16):
            kd = (A - B_val * n - C_val * n * n) & 0xFFFFFFFF
            pd = enc_dwords[n] ^ kd
            plains.append(pd)
            if n >= 2 and pd >= FILE_SIZE:
                all_ok = False

        if all_ok:
            print(f"\n  *** VALID: target_offset=0x{target:X}, B=0x{B_val:08X}, C=0x{C_val:08X}")
            print(f"      version={plains[1]}, first_offset=0x{plains[2]:X}")
            for n in range(min(16, len(plains))):
                print(f"      dw[{n:2d}] = 0x{plains[n]:08X} ({plains[n]:>12d})")

    print("\n\nDone phase 3.")

if __name__ == "__main__":
    main()
