"""
Phase 7: Fresh approach - examine encrypted data for structural patterns.

Key realization: ALL simple key formulas have failed. The key is either:
1. A precomputed table stored in the binary (likely 328 bytes based on pseudocode)
2. Generated by a complex algorithm we can't easily reverse

New strategy: Let's look at the ENCRYPTED data differently.
- Use statistical analysis
- Check if the key might be XORed with a KNOWN large plaintext block
- Look for the actual key table by analyzing the VRChat binary
"""

import struct
import os

METADATA_PATH = r"D:\Steam\steamapps\common\VRChat\VRChat_Data\il2cpp_data\Metadata\global-metadata.dat"
BINARY_PATH = r"D:\Steam\steamapps\common\VRChat\VRChat_Data\Native\GameAssembly.dll"
FILE_SIZE = 40_512_432

def read_header(path, size=1024):
    with open(path, "rb") as f:
        return f.read(size)

def main():
    data = read_header(METADATA_PATH)

    print("="*70)
    print("PHASE 7: Look for key table in GameAssembly.dll")
    print("="*70)

    # From the pseudocode: the decrypt function processes 328 bytes (0x148) of header.
    # After that, sections are decrypted with simpler per-section XOR.
    #
    # The header key is generated by the SIMD loop. For the NEW version,
    # the algorithm produces key[0..3] = [0x83, 0x67, 0xAF, 0xEC].
    #
    # Strategy: Search the binary for the byte sequence [0x83, 0x67, 0xAF, 0xEC]
    # in contexts that look like a key table (near the decrypt function).
    #
    # But first, let me look at the decrypt function's constants more carefully.
    # From the pseudocode, the FILENAME generation uses:
    #   xmmword_18B679930 = 0x4B repeated
    #   Constants: 0xDAD8DAD2, 0xD196D6D8, 0xA4DECAD8, 0xEAA2B6A0, 0xC8B3A7A1
    # These produce "global-metadata.dat"
    #
    # IDEA: What if the NEW decrypt constant is NOT 0x34 but something else,
    # AND the formula is NOT (i - const) but uses the filename bytes?
    #
    # What if: key[i] = (filename_byte[i % 20] - some_const) & 0xFF?

    fname = b"global-metadata.dat\x00"
    print(f"\nFilename bytes: {[f'0x{b:02X}' for b in fname[:20]]}")

    # Test: key[i] = (fname[i%20] - C) & 0xFF
    # key[0] = (0x67 - C) = 0x83 => C = 0x67-0x83 = -0x1C = 0xE4
    # key[1] = (0x6C - 0xE4) & 0xFF = (108-228)&0xFF = -120&0xFF = 0x88. Need 0x67. No.
    print("\n[Test] key[i] = (fname[i%20] - C): C=0xE4")
    print(f"  key[1] would be (0x{fname[1]:02X} - 0xE4)&0xFF = 0x{(fname[1]-0xE4)&0xFF:02X} (need 0x67)")

    # Test: key[i] = fname[i%20] XOR C
    # key[0] = 0x67 ^ C = 0x83 => C = 0xE4
    # key[1] = 0x6C ^ 0xE4 = 0x88. Need 0x67. No.
    print(f"\n[Test] key[i] = fname[i%20] XOR 0xE4:")
    print(f"  key[1] = 0x{fname[1]^0xE4:02X} (need 0x67)")

    # None of the filename-based approaches work.

    # PLAN B: Search the binary for the key bytes or related constants.
    # The binary is large (~100MB), but we can search efficiently.

    print("\n\n" + "="*70)
    print("SEARCHING GameAssembly.dll for key-related patterns")
    print("="*70)

    if not os.path.exists(BINARY_PATH):
        print(f"  Binary not found at {BINARY_PATH}")
        return

    binary_size = os.path.getsize(BINARY_PATH)
    print(f"  Binary size: {binary_size:,} bytes")

    # Read chunks around the decrypt function area
    # From pseudocode: decrypt function is around 0x180A7E880
    # Constants are around 0x18B678xxx
    # In a DLL, we need to account for image base.
    # Typical image base for 64-bit DLL: 0x180000000
    # So file offset for 0x18B678xxx would be ~0xB678xxx (after subtracting image base)
    # But sections have different file offsets vs virtual addresses.

    # Let's just search for the key bytes [83 67 AF EC] in the binary
    # and look at context around each hit.

    KEY_BYTES = bytes([0x83, 0x67, 0xAF, 0xEC])

    print(f"\n  Searching for byte pattern 83 67 AF EC...")
    hits = []
    CHUNK_SIZE = 4 * 1024 * 1024  # 4MB chunks
    with open(BINARY_PATH, "rb") as f:
        offset = 0
        prev_tail = b""
        while True:
            chunk = f.read(CHUNK_SIZE)
            if not chunk:
                break
            # Search in overlap region
            search_data = prev_tail + chunk
            pos = 0
            while True:
                idx = search_data.find(KEY_BYTES, pos)
                if idx == -1:
                    break
                actual_offset = offset - len(prev_tail) + idx
                hits.append(actual_offset)
                pos = idx + 1
            prev_tail = chunk[-16:]  # keep overlap for boundary matches
            offset += len(chunk)

    print(f"  Found {len(hits)} occurrences")
    if hits:
        # Show first 20 hits with context
        with open(BINARY_PATH, "rb") as f:
            for i, hit in enumerate(hits[:30]):
                f.seek(max(0, hit - 8))
                context = f.read(32)
                rel_pos = min(8, hit)
                print(f"  [{i:3d}] offset=0x{hit:08X}: ...{context[:rel_pos].hex(' ')} [{context[rel_pos:rel_pos+4].hex(' ')}] {context[rel_pos+4:].hex(' ')}...")

    # Also search for the reversed order (big-endian representation)
    KEY_BYTES_REV = bytes([0xEC, 0xAF, 0x67, 0x83])
    print(f"\n  Searching for reversed pattern EC AF 67 83...")
    hits_rev = []
    with open(BINARY_PATH, "rb") as f:
        offset = 0
        prev_tail = b""
        while True:
            chunk = f.read(CHUNK_SIZE)
            if not chunk:
                break
            search_data = prev_tail + chunk
            pos = 0
            while True:
                idx = search_data.find(KEY_BYTES_REV, pos)
                if idx == -1:
                    break
                actual_offset = offset - len(prev_tail) + idx
                hits_rev.append(actual_offset)
                pos = idx + 1
            prev_tail = chunk[-16:]
            offset += len(chunk)

    print(f"  Found {len(hits_rev)} occurrences")
    if hits_rev:
        with open(BINARY_PATH, "rb") as f:
            for i, hit in enumerate(hits_rev[:20]):
                f.seek(max(0, hit - 8))
                context = f.read(32)
                rel_pos = min(8, hit)
                print(f"  [{i:3d}] offset=0x{hit:08X}: {context.hex(' ')}")

    # Also look for the XOR mask constants from the filename generation
    # 0xDAD8DAD2 as bytes: D2 DA D8 DA
    print(f"\n  Searching for filename XOR constant D2 DA D8 DA...")
    FNAME_CONST = bytes([0xD2, 0xDA, 0xD8, 0xDA])
    hits_fname = []
    with open(BINARY_PATH, "rb") as f:
        offset = 0
        prev_tail = b""
        while True:
            chunk = f.read(CHUNK_SIZE)
            if not chunk:
                break
            search_data = prev_tail + chunk
            pos = 0
            while True:
                idx = search_data.find(FNAME_CONST, pos)
                if idx == -1:
                    break
                actual_offset = offset - len(prev_tail) + idx
                hits_fname.append(actual_offset)
                pos = idx + 1
            prev_tail = chunk[-16:]
            offset += len(chunk)

    print(f"  Found {len(hits_fname)} occurrences")
    if hits_fname:
        with open(BINARY_PATH, "rb") as f:
            for i, hit in enumerate(hits_fname[:10]):
                f.seek(max(0, hit - 16))
                context = f.read(64)
                print(f"  [{i:3d}] offset=0x{hit:08X}: {context[:16].hex(' ')} | {context[16:32].hex(' ')} | {context[32:48].hex(' ')} | {context[48:].hex(' ')}")

    # Search for 0x4B4B4B4B (the subtract constant from filename generation)
    print(f"\n  Searching for 4B 4B 4B 4B 4B 4B 4B 4B (xmmword constant)...")
    KB_CONST = bytes([0x4B] * 8)
    hits_4b = []
    with open(BINARY_PATH, "rb") as f:
        offset = 0
        prev_tail = b""
        while True:
            chunk = f.read(CHUNK_SIZE)
            if not chunk:
                break
            search_data = prev_tail + chunk
            pos = 0
            while True:
                idx = search_data.find(KB_CONST, pos)
                if idx == -1:
                    break
                actual_offset = offset - len(prev_tail) + idx
                hits_4b.append(actual_offset)
                pos = idx + 1
            prev_tail = chunk[-16:]
            offset += len(chunk)

    print(f"  Found {len(hits_4b)} occurrences")
    if hits_4b:
        with open(BINARY_PATH, "rb") as f:
            for i, hit in enumerate(hits_4b[:10]):
                f.seek(hit)
                context = f.read(32)
                print(f"  [{i:3d}] offset=0x{hit:08X}: {context.hex(' ')}")

    # Search for 34 34 34 34 34 34 34 34 (the decrypt subtract constant)
    print(f"\n  Searching for 34 34 34 34 34 34 34 34 (decrypt constant from old version)...")
    CONST_34 = bytes([0x34] * 8)
    hits_34 = []
    with open(BINARY_PATH, "rb") as f:
        offset = 0
        prev_tail = b""
        while True:
            chunk = f.read(CHUNK_SIZE)
            if not chunk:
                break
            search_data = prev_tail + chunk
            pos = 0
            while True:
                idx = search_data.find(CONST_34, pos)
                if idx == -1:
                    break
                actual_offset = offset - len(prev_tail) + idx
                hits_34.append(actual_offset)
                pos = idx + 1
            prev_tail = chunk[-16:]
            offset += len(chunk)

    print(f"  Found {len(hits_34)} occurrences")
    if hits_34:
        with open(BINARY_PATH, "rb") as f:
            for i, hit in enumerate(hits_34[:10]):
                f.seek(hit)
                context = f.read(32)
                print(f"  [{i:3d}] offset=0x{hit:08X}: {context.hex(' ')}")

    # Look near the decrypt constants for clues about the new algorithm
    # The old constant at 0x18B678BC0 maps to file offset ~0xB678BC0
    # But that's larger than most DLLs. Let's check.
    print(f"\n  Binary size check: 0x{binary_size:X}")
    if 0xB678BC0 < binary_size:
        print(f"  Offset 0xB678BC0 is within binary!")
        with open(BINARY_PATH, "rb") as f:
            f.seek(0xB678BC0)
            context = f.read(64)
            print(f"  Data at 0xB678BC0: {context.hex(' ')}")
    else:
        print(f"  Offset 0xB678BC0 exceeds binary size.")

    print("\n\nDone phase 7.")

if __name__ == "__main__":
    main()
